//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "strategy")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub asset: String,
    pub side: String,
    pub size: i64,
    pub leverage: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub condition: Json,
    pub stop_loss: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
