services:
  compose-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    ports:
      - "18888"
    expose:
      - "18889"
      - "18890"
    networks:
      - "aspire"
    restart: "always"
  postgres:
    image: "docker.io/library/postgres:17.6"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    expose:
      - "5432"
    networks:
      - "aspire"
  web-api:
    image: "${WEB_API_IMAGE}"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/db"
      PORT: "5051"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "web-api"
    ports:
      - "5051:5051"
    depends_on:
      postgres:
        condition: "service_started"
    networks:
      - "aspire"
  frontend:
    image: "${FRONTEND_IMAGE}"
    environment:
      PORT: "3000"
      HOSTNAME: "0.0.0.0"
      WEB_API_HTTP: "http://web-api:5051"
      services__web-api__http__0: "http://web-api:5051"
    ports:
      - "3000:3000"
    depends_on:
      web-api:
        condition: "service_started"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
